### ISSUE TITLE
Unknown request in queue while dequeuing

### ISSUE THREAD

**Issue by yuyuyu8818** [go-vgo/robotgo#280]
- Robotgo version (or commit ref): v0.90.2
- Go version:1.14.5
- Gcc version:10.1.0
- Operating system and bit: linux(manjaro) 64bit
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant

---

Program sometimes terminates with this error.
Please Help!!

```
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
index: xcb_io.c:163: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
SIGABRT: abort
PC=0x7fa0852cb355 m=4 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fa0852cb355
stack: frame={sp:0x7fa05d5a8a30, fp:0x0} stack=[0x7fa05cda9288,0x7fa05d5a8e88)
00007fa05d5a8930:  0000003000000002  0000007c0000006e 
00007fa05d5a8940:  0000000000000000  000000770000005b 
00007fa05d5a8950:  0000000000000000  00007fa085319220 
00007fa05d5a8960:  0000000800000000  0000000000000000 
00007fa05d5a8970:  0000000000000005  0000000000000007 
00007fa05d5a8980:  0000000000000070  0000000000000064 
00007fa05d5a8990:  00007fa000000007  0000000000000015 
00007fa05d5a89a0:  0000000000000090  0000000000000001 
00007fa05d5a89b0:  0000003100000007  00007fa054000020 
00007fa05d5a89c0:  00007fa054000bd0  0000000000000060 
00007fa05d5a89d0:  0000000000000060  00007fa054000bc0 
00007fa05d5a89e0:  0000000000000070  00007fa08531af66 
00007fa05d5a89f0:  333631a054000c34  b0cae782a5f3d800 
00007fa05d5a8a00:  00007fa054000bd0  00007fa05d5a8c90 
00007fa05d5a8a10:  000000000000005f  000000000000005f 
00007fa05d5a8a20:  0000000000000060  00007fa054000bd0 
00007fa05d5a8a30: <0000000000000000  00007fa08530d710 
00007fa05d5a8a40:  00007fa0fbad8000  00007fa054000bd0 
00007fa05d5a8a50:  00007fa054000bd0  00007fa054000bd0 
00007fa05d5a8a60:  00007fa054000bd0  00007fa054000c2f 
00007fa05d5a8a70:  00007fa054000c34  00007fa054000bd0 
00007fa05d5a8a80:  00007fa054000c34  0000000000000000 
00007fa05d5a8a90:  0000000000000000  0000000000000000 
00007fa05d5a8aa0:  0000000000000000  0000000000000000 
00007fa05d5a8ab0:  fffffffe7fffffff  ffffffffffffffff 
00007fa05d5a8ac0:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8ad0:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8ae0:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8af0:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8b00:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8b10:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8b20:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7fa0852cb355
stack: frame={sp:0x7fa05d5a8a30, fp:0x0} stack=[0x7fa05cda9288,0x7fa05d5a8e88)
00007fa05d5a8930:  0000003000000002  0000007c0000006e 
00007fa05d5a8940:  0000000000000000  000000770000005b 
00007fa05d5a8950:  0000000000000000  00007fa085319220 
00007fa05d5a8960:  0000000800000000  0000000000000000 
00007fa05d5a8970:  0000000000000005  0000000000000007 
00007fa05d5a8980:  0000000000000070  0000000000000064 
00007fa05d5a8990:  00007fa000000007  0000000000000015 
00007fa05d5a89a0:  0000000000000090  0000000000000001 
00007fa05d5a89b0:  0000003100000007  00007fa054000020 
00007fa05d5a89c0:  00007fa054000bd0  0000000000000060 
00007fa05d5a89d0:  0000000000000060  00007fa054000bc0 
00007fa05d5a89e0:  0000000000000070  00007fa08531af66 
00007fa05d5a89f0:  333631a054000c34  b0cae782a5f3d800 
00007fa05d5a8a00:  00007fa054000bd0  00007fa05d5a8c90 
00007fa05d5a8a10:  000000000000005f  000000000000005f 
00007fa05d5a8a20:  0000000000000060  00007fa054000bd0 
00007fa05d5a8a30: <0000000000000000  00007fa08530d710 
00007fa05d5a8a40:  00007fa0fbad8000  00007fa054000bd0 
00007fa05d5a8a50:  00007fa054000bd0  00007fa054000bd0 
00007fa05d5a8a60:  00007fa054000bd0  00007fa054000c2f 
00007fa05d5a8a70:  00007fa054000c34  00007fa054000bd0 
00007fa05d5a8a80:  00007fa054000c34  0000000000000000 
00007fa05d5a8a90:  0000000000000000  0000000000000000 
00007fa05d5a8aa0:  0000000000000000  0000000000000000 
00007fa05d5a8ab0:  fffffffe7fffffff  ffffffffffffffff 
00007fa05d5a8ac0:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8ad0:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8ae0:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8af0:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8b00:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8b10:  ffffffffffffffff  ffffffffffffffff 
00007fa05d5a8b20:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x6c2680, 0xc000057d80, 0x2500000000a0fcd8)
        /usr/lib/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000057d50 sp=0xc000057d18 pc=0x40c09b
github.com/robotn/gohook._Cfunc_stop_event(0xc000000000)
        _cgo_gotypes.go:136 +0x49 fp=0xc000057d80 sp=0xc000057d50 pc=0x4fd3b9
github.com/robotn/gohook.End()
        /home/yuyuyu/go/pkg/mod/github.com/robotn/gohook@v0.30.2/hook.go:246 +0x32 fp=0xc000057db0 sp=0xc000057d80 pc=0x4fe792
github.com/go-vgo/robotgo.AddEvents(0x75ddc6, 0x2, 0xc000057f68, 0x1, 0x1, 0x0)
        /home/yuyuyu/go/pkg/mod/github.com/go-vgo/robotgo@v0.90.2/hook.go:143 +0x1d5 fp=0xc000057e98 sp=0xc000057db0 pc=0x6b0e55
main.main()
        /home/yuyuyu/Desktop/shortcut-uuid/index.go:13 +0x8d fp=0xc000057f88 sp=0xc000057e98 pc=0x6b3cfd
runtime.main()
        /usr/lib/go/src/runtime/proc.go:203 +0x1fa fp=0xc000057fe0 sp=0xc000057f88 pc=0x43deea
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x46ab21

goroutine 9 [sleep]:
time.Sleep(0x2faf080)
        /usr/lib/go/src/runtime/time.go:188 +0xba
github.com/robotn/gohook.Start.func1()
        /home/yuyuyu/go/pkg/mod/github.com/robotn/gohook@v0.30.2/hook.go:234 +0x31
created by github.com/robotn/gohook.Start
        /home/yuyuyu/go/pkg/mod/github.com/robotn/gohook@v0.30.2/hook.go:227 +0x86

goroutine 19 [sleep]:
time.Sleep(0x2faf080)
        /usr/lib/go/src/runtime/time.go:188 +0xba
github.com/robotn/gohook.Start.func1()
        /home/yuyuyu/go/pkg/mod/github.com/robotn/gohook@v0.30.2/hook.go:234 +0x31
created by github.com/robotn/gohook.Start
        /home/yuyuyu/go/pkg/mod/github.com/robotn/gohook@v0.30.2/hook.go:227 +0x86

rax    0x0
rbx    0x7fa05d5a9700
rcx    0x7fa0852cb355
rdx    0x0
rdi    0x2
rsi    0x7fa05d5a8a30
rbp    0x7fa08541f0a8
rsp    0x7fa05d5a8a30
r8     0x0
r9     0x7fa05d5a8a30
r10    0x8
r11    0x246
r12    0x7fa085714623
r13    0xa3
r14    0x7fa08571464b
r15    0x7fa040004820
rip    0x7fa0852cb355
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

```
---

Source Code
```Go
package main

import (
	"github.com/atotto/clipboard"
	"github.com/go-vgo/robotgo"
	"github.com/google/uuid"
	"strings"
)

func main(){

	for{
		eve:=robotgo.AddEvents("f1","ctrl")
		if eve{
			clipboard.WriteAll(strings.Replace(uuid.New().String(),"-","",-1))
			//time.Sleep(time.Millisecond * 500)
			robotgo.KeyTap("v","ctrl")
			robotgo.StopEvent()
		}
	}

}
```

Build Script
```sh
GOOS=linux GOARCH=amd64 go build -o ./out/linux index.go
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -ldflags '-extldflags "-static"' -o ./out/windows index.go
```

**Comment by codemodify** [comment]
I got a similar XInitThreads error
getting mouse and keyboard on two different sockets, and they use robot go in different threads

how to fix this ?
or suggestion is to not do this in go routines but serialize access ?

**Comment by codemodify** [comment]
so basically, what I did is serialize access to robotgo functions like this

```golang
var robotgoMutex = &sync.Mutex{}

func WithRobotGo(callback func()) {
	robotgoMutex.Lock()
	defer robotgoMutex.Unlock()

	callback()
}
```
