### ISSUE TITLE
panic when lock screen

### ISSUE THREAD

**Issue by Ccheers** [go-vgo/robotgo#585]
- Robotgo version (or commit ref): 1.0.0-beta6
- Go version: 1.20.3
- Gcc version: 14.0.0
- Operating system and bit: OSx-arm64
- Resolution:
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
- Provide example code:

```Go
screenImg = robotgo.CaptureImg()

```
- Log gist:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1044a5098]

goroutine 1 [running]:
github.com/go-vgo/robotgo.ToBitmap(...)
	/Users/eric/GoProject/GoResource/pkg/mod/github.com/go-vgo/robotgo@v1.0.0-beta6/robotgo.go:368
github.com/go-vgo/robotgo.ToRGBA(0x0?)
	/Users/eric/GoProject/GoResource/pkg/mod/github.com/go-vgo/robotgo@v1.0.0-beta6/robotgo.go:400 +0x28
github.com/go-vgo/robotgo.ToImage(...)
	/Users/eric/GoProject/GoResource/pkg/mod/github.com/go-vgo/robotgo@v1.0.0-beta6/robotgo.go:395
github.com/go-vgo/robotgo.CaptureImg({0x0?, 0x6458da96?, 0x14000057c88?})
	/Users/eric/GoProject/GoResource/pkg/mod/github.com/go-vgo/robotgo@v1.0.0-beta6/robotgo.go:344 +0x54
github.com/Ccheers/onmyoji-go/internal/biz.(*Workflow).Run.func1({0x28?, 0x1045642e0?})
	/Users/eric/GoProject/onmyoji-go/internal/biz/workflow.go:100 +0x30
github.com/Ccheers/onmyoji-go/internal/pkg/fnx.FnCost({0x10456e090, 0x1400009b200}, {0x140000bc1e0, 0x28}, 0x14000057da8)
	/Users/eric/GoProject/onmyoji-go/internal/pkg/fnx/fn.go:12 +0x54
github.com/Ccheers/onmyoji-go/internal/biz.(*Workflow).Run(0x140000ee300, {0x10456e090, 0x1400009b200})
	/Users/eric/GoProject/onmyoji-go/internal/biz/workflow.go:99 +0xa4
main.(*Manager).work(0x140000f0800)
	/Users/eric/GoProject/onmyoji-go/cmd/manager.go:186 +0x214
main.main()
	/Users/eric/GoProject/onmyoji-go/cmd/main.go:58 +0xfc

## Description
panic when lock screen
...

**Comment by uiosun** [comment]
In other version, the save image panic still keep: (the param x/y/w/h is: `373 370 1295 470`, the bug is occasionally appear)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff62d08ca24]

goroutine 1 [running]:
github.com/go-vgo/robotgo.ToBitmap(...)
        C:/Users/UioSun/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.3/robotgo.go:397
github.com/go-vgo/robotgo.ToRGBA(0xc0003c73c8?)
        C:/Users/UioSun/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.3/robotgo.go:429 +0x24
github.com/go-vgo/robotgo.ToImage(...)
        C:/Users/UioSun/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.3/robotgo.go:424
click_modify/client.(*Client).savePng(0x0?, 0x175, 0x172, 0x50f, 0x1d6, {0x7ff62d187093, 0x10})
        D:/Code/Go/click_modify/client/login.go:230 +0x1b4
click_modify/client.(*Client).RefreshPositionLogical(0xc000126080, {0x4152867ee0a3d70a, 0x413c3383dc28f5c3, 0x41469e7c370a3d71, 0x412a239c00000000, 0x0, 0x0, {0x0, 0x0, 0x0}})
        D:/Code/Go/click_modify/client/refresh.go:113 +0x208
click_modify/client.(*Client).UserRefreshClient(0xc000126080, 0x10?)
        D:/Code/Go/click_modify/client/refresh.go:24 +0x21b
click_modify/client.(*Client).UserSetOrder(0xc000126080, 0xc0000ae520)
        D:/Code/Go/click_modify/client/trade.go:74 +0x79d
click_modify/client.(*Client).NewConnect(0xc000126080)
        D:/Code/Go/click_modify/client/bootstrap.go:124 +0x870
main.main()
        D:/Code/Go/click_modify/client.go:48 +0x272
