### ISSUE TITLE
How to use go-bindata in OpenBitmap?

### ISSUE THREAD

**Issue by wilon** [go-vgo/robotgo#93]
I use https://github.com/jteeuwen/go-bindata turn image to Go code.
Then how to use https://github.com/go-vgo/robotgo `OpenBitmap`?

```
----- Test Dir
 |-- asset/asset.go
 |-- main.go
 |-- test.png

$  go-bindata -o=asset/asset.go -pkg=asset ./test.png        // generates Go code from png
$  go run main.go

panic: interface conversion: interface {} is []uint8, not string

goroutine 1 [running]:
github.com/go-vgo/robotgo.OpenBitmap(0xc042067f18, 0x1, 0x1, 0x0)
        C:/Users/Administrator/go/src/github.com/go-vgo/robotgo/robotgo.go:766 +0x1a6
main.main()
        C:/Users/Administrator/go/src/test/main.go:14 +0xcd
exit status 2
```

main.go
```go
package main

import (
	"asset"
	"fmt"
	"reflect"

	"github.com/go-vgo/robotgo"
)

func main() {

	data, _ := asset.Asset("test.png")
	bitmap := robotgo.OpenBitmap(data)
	fmt.Println("...bitmap", bitmap, reflect.TypeOf(bitmap))

}

```

**Comment by vcaesar** [comment]
`bitmap := robotgo.OpenBitmap(string(data))`.

**Comment by wilon** [comment]
I soled the problem in other way.
And the func `TostringBitmap` return `*C.char` unuseful, see my Pr.

In my submission, all the upper case Func's params and returns should be `Golang type`, then it can easy to use.
